# Generated by Django 4.1.5 on 2023-02-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_ubicacion_contaminacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='contaminacion',
            field=models.FloatField(),
        ),
    ]
